### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by Espzai** [ingadhoc/docker-compose-odoo#11]
Hi,
The linked google Docs documentation is not in English.
i.e. https://docs.google.com/document/d/1nuX99v_ncfEfXlAAYVe85k9a1JbkXBVG_39GK5GGWzg/preview

Could you please make them in English? or make the document downloadable so we can translate with Google?

Thank you for your time and efforts.

Best regards.

**Comment by jjscarafia** [comment]
Hi! With this link you should be able to duplicate, dowonlad, etc
https://docs.google.com/document/d/1nuX99v_ncfEfXlAAYVe85k9a1JbkXBVG_39GK5GGWzg/edit
FYI This is a real opinionated and customized project. Not sure I would recommend it :)

**Comment by Espzai** [comment]
Hi,
Thank you for your response.
At the moment, I am in learning/ testing phase.

Anyway, I am still unable to copy/ download the document.

![Screenshot from 2023-06-24 13-37-51](https://github.com/ingadhoc/docker-compose-odoo/assets/34160546/039ca46a-2183-4454-a4ff-99ae080b79c6)

**Comment by jjscarafia** [comment]
Mm, it seams it's due to workspace set up.
Find attached a downladed version
[Uploading Manual compartido de uso de Odoo Docker Adhoc.docx…]()

**Comment by Espzai** [comment]
Thank you for your support and efforts.
But for some reasons, I am still unable to download this document. Either there is a problem with attachment or I don't have access rights to download it.

Sorry for too much bothering and thank you for your co-operation.
