### ISSUE TITLE
Question: Definir container_name no escala

### ISSUE THREAD

**Issue by ruslanguns** [ingadhoc/docker-compose-odoo#3]
Primero gracias por tu aporte, me ha servido mucho para configurar mejor mi receta para odoo y postgres.
Mi pregunta es en relación al comentario que haces que al definir un container_name no se podrá escalar. Podrías por favor comentarme un poco qué problema ocasionaria? es que hay información escasa en internet.

**Comment by jjscarafia** [comment]
Buenas, me alegro que haya ayudado. La verdad es que hace rato que no toco esa docker compose. Actualmente utilizamos ranhcer y este compose https://bitbucket.org/ingadhoc/rancher-catalog/src/27596f51f969fbab0cff1a2b754b19a85211dc95/templates/adhoc-odoo/10/?at=master

Saludos,
Juan

**Comment by ruslanguns** [comment]
Interesante ese compose muy completo yo hice uno cubriendo mis necesidades básicas, pero definitivamente voy a ver que cositas saco de ese que me compartiste. Un saludo!
